#!/bin/bash

host=`hostname`

if [ "$1" = "all" ]; then
    echo tv > /tmp/stompy.cmd
    sudo pkill -SIGUSR1 stompy
fi

if [ "$1" = "all" -o "$1" = "cifdb" ]; then
    echo "Releasing cifdb"
    sudo cp cifdb   /usr/sbin/cifdb
    DONE="cifdb"
fi

if [ "$1" = "all" -o "$1" = "jsondb" ]; then
    echo "Releasing jsondb"
    sudo cp jsondb   /usr/sbin/jsondb
    DONE="jsondb"
fi

if [ "$1" = "all" -o "$1" = "tscdb" ]; then
    echo "Releasing tscdb"
    sudo cp tscdb   /usr/sbin/tscdb
    DONE="tscdb"
fi

if [ "$1" = "all" -o "$1" = "archdb" ]; then
    echo "Releasing archdb"
    sudo cp archdb   /usr/sbin/archdb
    DONE="archdb"
fi

if [ "$1" = "all" -o "$1" = "corpusdb" ]; then
    echo "Releasing corpusdb"
    sudo cp corpusdb   /usr/sbin/corpusdb
    DONE="corpusdb"
fi

if [ "$1" = "all" -o "$1" = "smartdb" ]; then
    echo "Releasing smartdb"
    sudo cp smartdb   /usr/sbin/smartdb
    DONE="smartdb"
fi

if [ "$1" = "all" -o "$1" = "liverail" ]; then
    if [ "$host" = "friedbread" ]; then
        echo "Releasing liverail for friedbread"
        sudo cp liverail.cgi        /usr/lib/cgi-bin/liverail.cgi
        sudo cp liverail.css        /var/www/friedbread/auxy/liverail.css
        sudo cp liverail.js         /var/www/friedbread/auxy/liverail.js
    else
        echo "Releasing liverail"
        sudo cp liverail.cgi        /usr/lib/cgi-bin/liverail.cgi
        sudo cp liverail.css        /var/www/auxy/liverail.css
        sudo cp liverail.js         /var/www/auxy/liverail.js
    fi
    DONE="liverail"
fi

if [ "$1" = "all" -o "$1" = "railquery" ]; then
    if [ "$host" = "friedbread" ]; then
        echo "Releasing railquery for friedbread"
        sudo cp railquery.cgi        /usr/lib/cgi-bin/railquery.cgi
        sudo cp railquery.css        /var/www/friedbread/auxy/railquery.css
        sudo cp railquery.js         /var/www/friedbread/auxy/railquery.js
    else
        echo "Releasing railquery"
        sudo cp railquery.cgi        /usr/lib/cgi-bin/railquery.cgi
        sudo cp railquery.css        /var/www/auxy/railquery.css
        sudo cp railquery.js         /var/www/auxy/railquery.js
    fi
    DONE="railquery"
fi

if [ "$1" = "all" -o "$1" = "livesig" ]; then
    if [ "$host" = "friedbread" ]; then
        echo "Releasing livesig for friedbread"
        sudo cp livesig.cgi        /usr/lib/cgi-bin/livesig.cgi
        sudo cp livesig.css        /var/www/friedbread/auxy/livesig.css
        sudo cp livesig.js         /var/www/friedbread/auxy/livesig.js
        m4 livesig1.svg > /tmp/zzz.svg && sudo ./cpm /tmp/zzz.svg /var/www/friedbread/auxy/livesig1.svg
        m4 livesig2.svg > /tmp/zzz.svg && sudo ./cpm /tmp/zzz.svg /var/www/friedbread/auxy/livesig2.svg
        m4 livesig3.svg > /tmp/zzz.svg && sudo ./cpm /tmp/zzz.svg /var/www/friedbread/auxy/livesig3.svg
    else
        if [ "$host" = "oakwood" ]; then
            echo "Releasing livesig for oakwood"
            sudo cp livesig.cgi        /usr/lib/cgi-bin-pub/livesig.cgi
            sudo cp livesig.css        /var/www/auxy/livesig.css
            sudo cp livesig.js         /var/www/auxy/livesig.js
            m4 livesig1.svg > /tmp/zzz.svg && sudo ./cpm /tmp/zzz.svg /var/www/auxy/livesig1.svg
            m4 livesig2.svg > /tmp/zzz.svg && sudo ./cpm /tmp/zzz.svg /var/www/auxy/livesig2.svg
            m4 livesig3.svg > /tmp/zzz.svg && sudo ./cpm /tmp/zzz.svg /var/www/auxy/livesig3.svg
        else
            echo "Releasing livesig"
            sudo cp livesig.cgi        /usr/lib/cgi-bin/livesig.cgi
            sudo cp livesig.css        /var/www/auxy/livesig.css
            sudo cp livesig.js         /var/www/auxy/livesig.js
            m4 livesig1.svg > /tmp/zzz.svg && sudo cp /tmp/zzz.svg /var/www/auxy/livesig1.svg
            m4 livesig2.svg > /tmp/zzz.svg && sudo cp /tmp/zzz.svg /var/www/auxy/livesig2.svg
            m4 livesig3.svg > /tmp/zzz.svg && sudo cp /tmp/zzz.svg /var/www/auxy/livesig3.svg
        fi
    fi
    DONE="livesig"
fi

if [ "$1" = "all" -o "$1" = "dump-rail" ]; then
    if [ "$host" = "friedbread" ]; then
        echo "Releasing dump-rail for friedbread"
        sudo cp dump-rail-fb /usr/sbin/dump-rail 
    else
        echo "Releasing dump-rail"
        sudo cp dump-rail /usr/sbin/dump-rail 
    fi
    DONE="dump-rail"
fi

if [ "$1" = "all" -o "$1" = "stompy" ]; then
    echo "Releasing stompy"
    sudo /etc/init.d/stompy stop
    sleep 4 
    sudo cp stompy /usr/sbin/stompy 
    sudo /etc/init.d/stompy start
    DONE="vstpdb"
fi

if [ "$1" = "all" -o "$1" = "vstpdb" ]; then
    echo "Releasing vstpdb"
    sudo /etc/init.d/vstpdb stop
    sleep 4 
    sudo cp vstpdb /usr/sbin/vstpdb 
    sudo /etc/init.d/vstpdb start
    DONE="vstpdb"
fi

if [ "$1" = "all" -o "$1" = "trustdb" ]; then
    echo "Releasing trustdb"
    sudo /etc/init.d/trustdb stop
    sleep 4 
    sudo cp trustdb /usr/sbin/trustdb 
    sudo /etc/init.d/trustdb start
    DONE="trustdb"
fi

if [ "$1" = "all" -o "$1" = "tddb" ]; then
    echo "Releasing tddb"
    sudo /etc/init.d/tddb stop
    sleep 4 
    sudo cp tddb /usr/sbin/tddb 
    sudo /etc/init.d/tddb start
    DONE="tddb"
fi

if [ "$1" = "all" -o "$1" = "limed" ]; then
    echo "Releasing limed"
    sudo /etc/init.d/limed stop
    sleep 4 
    if [ "$host" = "friedbread" ]; then
        sudo cp limed /usr/sbin/limed 
        sudo cp limed.css        /var/www/friedbread/auxy/limed.css
    else
        sudo cp limed /usr/sbin/limed 
        sudo cp limed.css        /var/www/auxy/limed.css
    fi
    sudo /etc/init.d/limed start
    DONE="limed"
fi

if [ "$DONE" = "" ]; then
    echo "Usage:  $0 cifdb|archdb|corpusdb|vstpdb|trustdb|tddb|liverail|livesig|railquery|stompy|limed|all    -    Release specified unit or all."
fi

