#!/bin/bash

host=`hostname`

if [ "$1" = "all" ]; then
    echo tv > /tmp/stompy.cmd
    sudo pkill -SIGUSR1 stompy
fi

if [ "$1" = "all" -o "$1" = "cifdb" ]; then
    echo "Releasing cifdb"
    sudo cp cifdb   /usr/sbin/cifdb
    DONE="cifdb"
fi

if [ "$1" = "all" -o "$1" = "archdb" ]; then
    echo "Releasing archdb"
    sudo cp archdb   /usr/sbin/archdb
    DONE="archdb"
fi

if [ "$1" = "all" -o "$1" = "corpusdb" ]; then
    echo "Releasing corpusdb"
    sudo cp corpusdb   /usr/sbin/corpusdb
    DONE="corpusdb"
fi

if [ "$1" = "all" -o "$1" = "liverail" ]; then
    if [ "$host" = "friedbread.liverpub.com" ]; then
        echo "Releasing liverail for friedbread"
        sudo cp liverail.cgi        /usr/lib/cgi-bin/liverail.cgi
        cp liverail.css        /var/www/friedbread/liverail.css
        cp liverail.js         /var/www/friedbread/liverail.js
    else
        echo "Releasing liverail"
        sudo cp liverail.cgi        /usr/lib/cgi-bin/liverail.cgi
        sudo cp liverail.css        /var/www/liverail.css
        sudo cp liverail.js         /var/www/liverail.js
    fi
    DONE="liverail"
fi

if [ "$1" = "all" -o "$1" = "livesig" ]; then
    if [ "$host" = "friedbread.liverpub.com" ]; then
        echo "Releasing livesig for friedbread"
        sudo cp livesig.cgi        /usr/lib/cgi-bin/livesig.cgi
        cp livesig.css        /var/www/friedbread/livesig.css
        cp livesig.js         /var/www/friedbread/livesig.js
        cp livesig.svg        /var/www/friedbread/livesig.svg
    else
        if [ "$host" = "oakwood" ]; then
            echo "Releasing livesig for oakwood"
            sudo cp livesig.cgi        /usr/lib/cgi-bin-pub/livesig.cgi
            sudo cp livesig.css        /var/www/livesig.css
            sudo cp livesig.js         /var/www/livesig.js
            sudo cp livesig.svg        /var/www/livesig.svg
        else
            echo "Releasing livesig"
            sudo cp livesig.cgi        /usr/lib/cgi-bin/livesig.cgi
            sudo cp livesig.css        /var/www/livesig.css
            sudo cp livesig.js         /var/www/livesig.js
            sudo cp livesig.svg        /var/www/livesig.svg
        fi
    fi
    DONE="livesig"
fi

if [ "$1" = "all" -o "$1" = "dump-rail" ]; then
    if [ "$host" = "friedbread.liverpub.com" ]; then
        echo "Releasing dump-rail for friedbread"
        sudo cp dump-rail-fb /usr/sbin/dump-rail 
    else
        echo "Releasing dump-rail"
        sudo cp dump-rail /usr/sbin/dump-rail 
    fi
    DONE="dump-rail"
fi

if [ "$1" = "all" -o "$1" = "stompy" ]; then
    echo "Releasing stompy"
    sudo /etc/init.d/stompy stop
    sleep 4 
    sudo cp stompy /usr/sbin/stompy 
    sudo /etc/init.d/stompy start
    DONE="vstpdb"
fi

if [ "$1" = "all" -o "$1" = "vstpdb" ]; then
    echo "Releasing vstpdb"
    sudo /etc/init.d/vstpdb stop
    sleep 4 
    sudo cp vstpdb /usr/sbin/vstpdb 
    sudo /etc/init.d/vstpdb start
    DONE="vstpdb"
fi

if [ "$1" = "all" -o "$1" = "trustdb" ]; then
    echo "Releasing trustdb"
    sudo /etc/init.d/trustdb stop
    sleep 4 
    sudo cp trustdb /usr/sbin/trustdb 
    sudo /etc/init.d/trustdb start
    DONE="trustdb"
fi

if [ "$1" = "all" -o "$1" = "tddb" ]; then
    echo "Releasing tddb"
    sudo /etc/init.d/tddb stop
    sleep 4 
    sudo cp tddb /usr/sbin/tddb 
    sudo /etc/init.d/tddb start
    DONE="tddb"
fi

if [ "$DONE" = "" ]; then
    echo "Usage:  $0 cifdb|archdb|corpusdb|vstpdb|trustdb|tddb|liverail|livesig|stompy|all    -    Release specified unit or all."
fi

